// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: proto/grpcm.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string `protobuf:"bytes,1,opt,name=A,proto3" json:"A,omitempty"`
	B string `protobuf:"bytes,2,opt,name=B,proto3" json:"B,omitempty"`
}

func (x *StringRequest) Reset() {
	*x = StringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringRequest) ProtoMessage() {}

func (x *StringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringRequest.ProtoReflect.Descriptor instead.
func (*StringRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcm_proto_rawDescGZIP(), []int{0}
}

func (x *StringRequest) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *StringRequest) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

type StringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
}

func (x *StringResponse) Reset() {
	*x = StringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpcm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringResponse) ProtoMessage() {}

func (x *StringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringResponse.ProtoReflect.Descriptor instead.
func (*StringResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpcm_proto_rawDescGZIP(), []int{1}
}

func (x *StringResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *StringResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_proto_grpcm_proto protoreflect.FileDescriptor

var file_proto_grpcm_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2b, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x41, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x01, 0x41, 0x12, 0x0c, 0x0a, 0x01, 0x42, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x01, 0x42, 0x22, 0x34, 0x0a, 0x0e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x72, 0x72, 0x32, 0xe7, 0x01, 0x0a, 0x0e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x2f, 0x0a,
	0x06, 0x43, 0x6f, 0x6e, 0x63, 0x61, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d,
	0x0a, 0x12, 0x4c, 0x6f, 0x74, 0x73, 0x4f, 0x66, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x30, 0x0a,
	0x05, 0x4c, 0x6f, 0x73, 0x74, 0x52, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12,
	0x33, 0x0a, 0x06, 0x4c, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_grpcm_proto_rawDescOnce sync.Once
	file_proto_grpcm_proto_rawDescData = file_proto_grpcm_proto_rawDesc
)

func file_proto_grpcm_proto_rawDescGZIP() []byte {
	file_proto_grpcm_proto_rawDescOnce.Do(func() {
		file_proto_grpcm_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_grpcm_proto_rawDescData)
	})
	return file_proto_grpcm_proto_rawDescData
}

var file_proto_grpcm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_grpcm_proto_goTypes = []interface{}{
	(*StringRequest)(nil),  // 0: pb.StringRequest
	(*StringResponse)(nil), // 1: pb.StringResponse
}
var file_proto_grpcm_proto_depIdxs = []int32{
	0, // 0: pb.StringServices.Concat:input_type -> pb.StringRequest
	0, // 1: pb.StringServices.LotsOfserverStream:input_type -> pb.StringRequest
	0, // 2: pb.StringServices.LostR:input_type -> pb.StringRequest
	0, // 3: pb.StringServices.LostRe:input_type -> pb.StringRequest
	1, // 4: pb.StringServices.Concat:output_type -> pb.StringResponse
	1, // 5: pb.StringServices.LotsOfserverStream:output_type -> pb.StringResponse
	1, // 6: pb.StringServices.LostR:output_type -> pb.StringResponse
	1, // 7: pb.StringServices.LostRe:output_type -> pb.StringResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_grpcm_proto_init() }
func file_proto_grpcm_proto_init() {
	if File_proto_grpcm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_grpcm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpcm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_grpcm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grpcm_proto_goTypes,
		DependencyIndexes: file_proto_grpcm_proto_depIdxs,
		MessageInfos:      file_proto_grpcm_proto_msgTypes,
	}.Build()
	File_proto_grpcm_proto = out.File
	file_proto_grpcm_proto_rawDesc = nil
	file_proto_grpcm_proto_goTypes = nil
	file_proto_grpcm_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StringServicesClient is the client API for StringServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StringServicesClient interface {
	Concat(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringResponse, error)
	LotsOfserverStream(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (StringServices_LotsOfserverStreamClient, error)
	LostR(ctx context.Context, opts ...grpc.CallOption) (StringServices_LostRClient, error)
	LostRe(ctx context.Context, opts ...grpc.CallOption) (StringServices_LostReClient, error)
}

type stringServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewStringServicesClient(cc grpc.ClientConnInterface) StringServicesClient {
	return &stringServicesClient{cc}
}

func (c *stringServicesClient) Concat(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringResponse, error) {
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, "/pb.StringServices/Concat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stringServicesClient) LotsOfserverStream(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (StringServices_LotsOfserverStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StringServices_serviceDesc.Streams[0], "/pb.StringServices/LotsOfserverStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &stringServicesLotsOfserverStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StringServices_LotsOfserverStreamClient interface {
	Recv() (*StringResponse, error)
	grpc.ClientStream
}

type stringServicesLotsOfserverStreamClient struct {
	grpc.ClientStream
}

func (x *stringServicesLotsOfserverStreamClient) Recv() (*StringResponse, error) {
	m := new(StringResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stringServicesClient) LostR(ctx context.Context, opts ...grpc.CallOption) (StringServices_LostRClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StringServices_serviceDesc.Streams[1], "/pb.StringServices/LostR", opts...)
	if err != nil {
		return nil, err
	}
	x := &stringServicesLostRClient{stream}
	return x, nil
}

type StringServices_LostRClient interface {
	Send(*StringRequest) error
	CloseAndRecv() (*StringResponse, error)
	grpc.ClientStream
}

type stringServicesLostRClient struct {
	grpc.ClientStream
}

func (x *stringServicesLostRClient) Send(m *StringRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *stringServicesLostRClient) CloseAndRecv() (*StringResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StringResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stringServicesClient) LostRe(ctx context.Context, opts ...grpc.CallOption) (StringServices_LostReClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StringServices_serviceDesc.Streams[2], "/pb.StringServices/LostRe", opts...)
	if err != nil {
		return nil, err
	}
	x := &stringServicesLostReClient{stream}
	return x, nil
}

type StringServices_LostReClient interface {
	Send(*StringRequest) error
	Recv() (*StringResponse, error)
	grpc.ClientStream
}

type stringServicesLostReClient struct {
	grpc.ClientStream
}

func (x *stringServicesLostReClient) Send(m *StringRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *stringServicesLostReClient) Recv() (*StringResponse, error) {
	m := new(StringResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StringServicesServer is the server API for StringServices service.
type StringServicesServer interface {
	Concat(context.Context, *StringRequest) (*StringResponse, error)
	LotsOfserverStream(*StringRequest, StringServices_LotsOfserverStreamServer) error
	LostR(StringServices_LostRServer) error
	LostRe(StringServices_LostReServer) error
}

// UnimplementedStringServicesServer can be embedded to have forward compatible implementations.
type UnimplementedStringServicesServer struct {
}

func (*UnimplementedStringServicesServer) Concat(context.Context, *StringRequest) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Concat not implemented")
}
func (*UnimplementedStringServicesServer) LotsOfserverStream(*StringRequest, StringServices_LotsOfserverStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method LotsOfserverStream not implemented")
}
func (*UnimplementedStringServicesServer) LostR(StringServices_LostRServer) error {
	return status.Errorf(codes.Unimplemented, "method LostR not implemented")
}
func (*UnimplementedStringServicesServer) LostRe(StringServices_LostReServer) error {
	return status.Errorf(codes.Unimplemented, "method LostRe not implemented")
}

func RegisterStringServicesServer(s *grpc.Server, srv StringServicesServer) {
	s.RegisterService(&_StringServices_serviceDesc, srv)
}

func _StringServices_Concat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StringServicesServer).Concat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StringServices/Concat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StringServicesServer).Concat(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StringServices_LotsOfserverStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StringRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StringServicesServer).LotsOfserverStream(m, &stringServicesLotsOfserverStreamServer{stream})
}

type StringServices_LotsOfserverStreamServer interface {
	Send(*StringResponse) error
	grpc.ServerStream
}

type stringServicesLotsOfserverStreamServer struct {
	grpc.ServerStream
}

func (x *stringServicesLotsOfserverStreamServer) Send(m *StringResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StringServices_LostR_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StringServicesServer).LostR(&stringServicesLostRServer{stream})
}

type StringServices_LostRServer interface {
	SendAndClose(*StringResponse) error
	Recv() (*StringRequest, error)
	grpc.ServerStream
}

type stringServicesLostRServer struct {
	grpc.ServerStream
}

func (x *stringServicesLostRServer) SendAndClose(m *StringResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *stringServicesLostRServer) Recv() (*StringRequest, error) {
	m := new(StringRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StringServices_LostRe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StringServicesServer).LostRe(&stringServicesLostReServer{stream})
}

type StringServices_LostReServer interface {
	Send(*StringResponse) error
	Recv() (*StringRequest, error)
	grpc.ServerStream
}

type stringServicesLostReServer struct {
	grpc.ServerStream
}

func (x *stringServicesLostReServer) Send(m *StringResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *stringServicesLostReServer) Recv() (*StringRequest, error) {
	m := new(StringRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _StringServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.StringServices",
	HandlerType: (*StringServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Concat",
			Handler:    _StringServices_Concat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LotsOfserverStream",
			Handler:       _StringServices_LotsOfserverStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LostR",
			Handler:       _StringServices_LostR_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "LostRe",
			Handler:       _StringServices_LostRe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/grpcm.proto",
}
